name: Bienvenida

on: [pull_request_target]

jobs: 
  welcome:
    runs-on: ubuntu-latest
    permissions:
      pull-request: write
    steps:
    - uses: actions/first-interacion@v1
    with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
      issue-message: "Sorry, something went wrong, try again..."
      pr-message: "PR merged!"